### ISSUE TITLE
Polymer observables: Dushek_2014.bngl, polymer.bngl

### ISSUE THREAD

**Issue by vcellmike** [noahlb123/bngl-visualizer#8]
polymer.bngl

Species Agreaterthan100 @c0:A()>100 
display  @c0:A()>100 in BNGL code

**Comment by vcellmike** [comment]
Dushek_2011.bngl

B==2  should be displayed as a molecule B (with all states being grey)==2. BNGL code is B==2, not B==2()

**Comment by noahlb123** [comment]
Fixed issue with B==2.
Do you want polymer lengths (>100) displayed in the visualizations? I believe they are already displayed in the BNGL code.
